// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5Pt5tsDdzW7gVobtmRR-POjGCShXBm0',
    appId: '1:520956764745:web:438c50ad9c51bf60f25598',
    messagingSenderId: '520956764745',
    projectId: 'hopehub-4eb4a',
    authDomain: 'hopehub-4eb4a.firebaseapp.com',
    storageBucket: 'hopehub-4eb4a.firebasestorage.app',
    measurementId: 'G-D6WZPSFL1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiiKsAPUvWvmPW5qyYYi9OBL-JDzgb8zY',
    appId: '1:520956764745:android:ec4925fe64d58dbbf25598',
    messagingSenderId: '520956764745',
    projectId: 'hopehub-4eb4a',
    storageBucket: 'hopehub-4eb4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoBVtlMZQXWl-SGQ5DVoVrmzry2Y9rKpI',
    appId: '1:520956764745:ios:e11c900e5f688975f25598',
    messagingSenderId: '520956764745',
    projectId: 'hopehub-4eb4a',
    storageBucket: 'hopehub-4eb4a.firebasestorage.app',
    iosBundleId: 'com.example.hopehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoBVtlMZQXWl-SGQ5DVoVrmzry2Y9rKpI',
    appId: '1:520956764745:ios:e11c900e5f688975f25598',
    messagingSenderId: '520956764745',
    projectId: 'hopehub-4eb4a',
    storageBucket: 'hopehub-4eb4a.firebasestorage.app',
    iosBundleId: 'com.example.hopehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN5Pt5tsDdzW7gVobtmRR-POjGCShXBm0',
    appId: '1:520956764745:web:e3d3505eb48ab879f25598',
    messagingSenderId: '520956764745',
    projectId: 'hopehub-4eb4a',
    authDomain: 'hopehub-4eb4a.firebaseapp.com',
    storageBucket: 'hopehub-4eb4a.firebasestorage.app',
    measurementId: 'G-TE385XQQ29',
  );
}
